"""Where operator verification inputs live.

    verification/operators/<operator>/
        base/<domain>/<operator>.json                   hand-written base design config (only for operators whose variants are generated)
        variants/<domain>/<operator>[__<variant>].json  the design configs that are verified (generated by gen_variants.py, or hand-written
                                                        for operators with no compute-affecting parameter, where the file is <operator>.json)
        verif_config.json                               (optional) this operator's verification settings; defaults come from paper_verif.json
        input.txt                                       (optional) static inputs

`<operator>` is the generator op name (gemm, vmm, mmv, dot_product, conv, batchnorm, maxpool, adaptive_avgpool, matrix_add, mha, swa,
matmul, layernorm, rmsnorm, elementwise_mult, dropout, activation): the 17 operators of the paper's Table 2. The file stem
(`activation__relu`, `vmm__bias0`, `batchnorm`) is unique within a domain and is the variant's historical short id.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OPERATORS_DIR = os.path.join(HERE, "operators")
DOMAINS = ("gemm", "conv", "llm")


def variant_name(operator, stem):
    """'vmm__bias0' -> 'bias0'; the bare 'batchnorm' -> 'default'."""
    return "default" if stem == operator else stem[len(operator) + 2:]


def variants(domain=None, operator=None):
    """All verified design configs as dicts: domain, operator, variant, stem, id (ops/<domain>/<stem>), path."""
    out = []
    if not os.path.isdir(OPERATORS_DIR):
        return out
    for op in sorted(os.listdir(OPERATORS_DIR)):
        vdir = os.path.join(OPERATORS_DIR, op, "variants")
        if not os.path.isdir(vdir) or (operator and op != operator):
            continue
        for d in sorted(os.listdir(vdir)):
            if domain and d != domain:
                continue
            ddir = os.path.join(vdir, d)
            for fn in sorted(os.listdir(ddir)):
                if fn.endswith(".json"):
                    stem = os.path.splitext(fn)[0]
                    out.append({"domain": d, "operator": op, "variant": variant_name(op, stem), "stem": stem,
                                "id": f"ops/{d}/{stem}", "path": os.path.join(ddir, fn)})
    return sorted(out, key=lambda x: (x["domain"], x["stem"]))


def base_path(operator, domain):
    return os.path.join(OPERATORS_DIR, operator, "base", domain, f"{operator}.json")
