"""Full-model verification table (Hanqiu's production-model results) -> verification/paper_runs/verif_fullmodel.tex

    python verification/paper_runs/make_fullmodel_table.py

Source: scale_models/existing_model_verification/results/validation_summary.json (read only).
Per model and format: final-logit max abs error and relative L2 (percent; for Llama the maximum over the prefill and decode calls),
the FP64 verdict (relative L2 <= 5% at every observed tensor) and the number of mismatching integer codes against the fixed-point reference.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "scale_models", "existing_model_verification", "results", "validation_summary.json")
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "verif_fullmodel.tex")
FORMATS = [("ap_fixed<16,5>", r"\texttt{<16,5>}"), ("ap_fixed<32,10>", r"\texttt{<32,10>}")]


def name(model):
    if model.startswith("resnet"):
        depth, kind = model[len("resnet"):].split("_")
        return f"ResNet-{depth} ({kind})"
    return "Llama-3-8B, cache " + ("8192" if "8192" in model else "2048")


def f(x):
    if x is None:
        return "--"
    m, e = f"{x:.2e}".split("e")
    return m if int(e) == 0 else rf"{m}\!\times\!10^{{{int(e)}}}"


def logits(run):
    L = run["logits"]
    calls = list(L.values()) if "max_abs" not in L else [L]
    return max(c["max_abs"] for c in calls), max(c["relative_l2"] for c in calls) * 100


def main():
    runs = json.load(open(SRC))["runs"]
    by = {(r["model"], r["precision"]): r for r in runs}
    models = sorted({r["model"] for r in runs}, key=lambda m: (m.startswith("llama"), int("".join(c for c in m.split("_")[0] if c.isdigit()) or 0), m))
    cols = "l" + "rrc" * len(FORMATS)
    L = [r"\begin{table*}[t]", r"\centering", r"\small",
         r"\caption{Full-model verification (Vitis HLS C simulation of the saved generated accelerators, synthetic parameters, one seed). "
         r"Final-logit maximum absolute error and relative L2 error (\%) against an independent FP64 PyTorch graph; for Llama, the maximum over "
         r"the 4-token prefill and 2 decode calls. FP64 verdict: relative L2 $\leq 5\%$ at every observed tensor. All variants match the "
         r"fixed-point reference at every integer code (0 mismatches).}",
         r"\label{tab:verif-fullmodel}", r"\begin{tabular}{" + cols + "}", r"\toprule",
         "Model & " + " & ".join(rf"\multicolumn{{3}}{{c}}{{{t}}}" for _, t in FORMATS) + r" \\",
         r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
         " & " + " & ".join(r"max abs & rel.\ L2 (\%) & FP64" for _ in FORMATS) + r" \\", r"\midrule"]
    for m in models:
        cells = []
        for p, _ in FORMATS:
            r = by.get((m, p))
            if r is None:
                cells += ["--"] * 3
                continue
            assert r["mismatching_codes"] == 0 and r["implementation_verdict"] == "PASS", (m, p)
            mx, l2 = logits(r)
            cells += [f"${f(mx)}$", f"${f(l2)}$", "pass" if r["mathematical_verdict"] == "PASS" else "fail"]
        L.append(name(m) + " & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    open(OUT, "w").write("% Auto-generated by verification/paper_runs/make_fullmodel_table.py -- do not edit by hand.\n"
                         "% Needs: booktabs.\n" + "\n".join(L) + "\n")
    print(f"wrote {OUT} ({len(models)} models)")


main()
